//<auto-generated>
//</auto-generated>
namespace GestionNovedades.Model.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddTeam : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Radicado", "IdEntrega", "dbo.Empleados");
            DropForeignKey("dbo.Radicado", "IdDesarrollo", "dbo.Empleados");
            DropForeignKey("dbo.Radicado", "IdCalidad", "dbo.Empleados");
            DropForeignKey("dbo.Radicado", "IdRequisitos", "dbo.Empleados");
            DropIndex("dbo.Radicado", new[] { "IdRequisitos" });
            DropIndex("dbo.Radicado", new[] { "IdDesarrollo" });
            DropIndex("dbo.Radicado", new[] { "IdCalidad" });
            DropIndex("dbo.Radicado", new[] { "IdEntrega" });
            CreateTable(
                "dbo.Equipo",
                c => new
                    {
                        IdEquipo = c.Guid(nullable: false, identity: true),
                        IdRadicado = c.Guid(nullable: false),
                        EmpleadoId = c.Guid(nullable: false),
                    })
                .PrimaryKey(t => t.IdEquipo)
                .ForeignKey("dbo.Empleados", t => t.EmpleadoId, cascadeDelete: true)
                .ForeignKey("dbo.Radicado", t => t.IdRadicado, cascadeDelete: true)
                .Index(t => t.IdRadicado)
                .Index(t => t.EmpleadoId);
            
            DropColumn("dbo.Radicado", "IdRequisitos");
            DropColumn("dbo.Radicado", "IdDesarrollo");
            DropColumn("dbo.Radicado", "IdCalidad");
            DropColumn("dbo.Radicado", "IdEntrega");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Radicado", "IdEntrega", c => c.Guid());
            AddColumn("dbo.Radicado", "IdCalidad", c => c.Guid());
            AddColumn("dbo.Radicado", "IdDesarrollo", c => c.Guid());
            AddColumn("dbo.Radicado", "IdRequisitos", c => c.Guid());
            DropForeignKey("dbo.Equipo", "IdRadicado", "dbo.Radicado");
            DropForeignKey("dbo.Equipo", "EmpleadoId", "dbo.Empleados");
            DropIndex("dbo.Equipo", new[] { "EmpleadoId" });
            DropIndex("dbo.Equipo", new[] { "IdRadicado" });
            DropTable("dbo.Equipo");
            CreateIndex("dbo.Radicado", "IdEntrega");
            CreateIndex("dbo.Radicado", "IdCalidad");
            CreateIndex("dbo.Radicado", "IdDesarrollo");
            CreateIndex("dbo.Radicado", "IdRequisitos");
            AddForeignKey("dbo.Radicado", "IdRequisitos", "dbo.Empleados", "EmpleadoId");
            AddForeignKey("dbo.Radicado", "IdCalidad", "dbo.Empleados", "EmpleadoId");
            AddForeignKey("dbo.Radicado", "IdDesarrollo", "dbo.Empleados", "EmpleadoId");
            AddForeignKey("dbo.Radicado", "IdEntrega", "dbo.Empleados", "EmpleadoId");
        }
    }
}
