//<auto-generated>
//</auto-generated>
namespace GestionNovedades.Model.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class InitMigration : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Companias",
                c => new
                    {
                        CompanyId = c.Guid(nullable: false, identity: true),
                        IdentificacionCompania = c.String(maxLength: 10, unicode: false),
                        NombreCompania = c.String(maxLength: 70, unicode: false),
                    })
                .PrimaryKey(t => t.CompanyId);
            
            CreateTable(
                "dbo.Radicado",
                c => new
                    {
                        IdRadicado = c.Guid(nullable: false, identity: true),
                        NumeroProceso = c.String(maxLength: 10, unicode: false),
                        IdCompaniaReporta = c.Guid(nullable: false),
                        FechaInicio = c.DateTime(nullable: false, storeType: "smalldatetime"),
                        Estado = c.Byte(nullable: false),
                        FechaUltimaRevision = c.DateTime(nullable: false, storeType: "smalldatetime"),
                        FechaFinaliza = c.DateTime(nullable: false, storeType: "smalldatetime"),
                        FechaEntrega = c.DateTime(nullable: false, storeType: "smalldatetime"),
                        Descripcion = c.String(maxLength: 500, unicode: false),
                        IdRequisitos = c.Guid(),
                        IdDesarrollo = c.Guid(),
                        IdCalidad = c.Guid(),
                        IdEntrega = c.Guid(),
                    })
                .PrimaryKey(t => t.IdRadicado)
                .ForeignKey("dbo.Companias", t => t.IdCompaniaReporta, cascadeDelete: true)
                .ForeignKey("dbo.Empleados", t => t.IdEntrega)
                .ForeignKey("dbo.Empleados", t => t.IdDesarrollo)
                .ForeignKey("dbo.Empleados", t => t.IdCalidad)
                .ForeignKey("dbo.Empleados", t => t.IdRequisitos)
                .Index(t => t.IdCompaniaReporta)
                .Index(t => t.IdRequisitos)
                .Index(t => t.IdDesarrollo)
                .Index(t => t.IdCalidad)
                .Index(t => t.IdEntrega);
            
            CreateTable(
                "dbo.Empleados",
                c => new
                    {
                        EmpleadoId = c.Guid(nullable: false, identity: true),
                        IdentificacionEmpleado = c.String(maxLength: 20, unicode: false),
                        NombreCompleto = c.String(maxLength: 200, unicode: false),
                        IdRole = c.Guid(nullable: false),
                    })
                .PrimaryKey(t => t.EmpleadoId)
                .ForeignKey("dbo.Roles", t => t.IdRole, cascadeDelete: true)
                .Index(t => t.IdRole);
            
            CreateTable(
                "dbo.Roles",
                c => new
                    {
                        IdRol = c.Guid(nullable: false, identity: true),
                        DescripcionRol = c.String(maxLength: 15, unicode: false),
                    })
                .PrimaryKey(t => t.IdRol);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Radicado", "IdRequisitos", "dbo.Empleados");
            DropForeignKey("dbo.Radicado", "IdCalidad", "dbo.Empleados");
            DropForeignKey("dbo.Radicado", "IdDesarrollo", "dbo.Empleados");
            DropForeignKey("dbo.Radicado", "IdEntrega", "dbo.Empleados");
            DropForeignKey("dbo.Empleados", "IdRole", "dbo.Roles");
            DropForeignKey("dbo.Radicado", "IdCompaniaReporta", "dbo.Companias");
            DropIndex("dbo.Empleados", new[] { "IdRole" });
            DropIndex("dbo.Radicado", new[] { "IdEntrega" });
            DropIndex("dbo.Radicado", new[] { "IdCalidad" });
            DropIndex("dbo.Radicado", new[] { "IdDesarrollo" });
            DropIndex("dbo.Radicado", new[] { "IdRequisitos" });
            DropIndex("dbo.Radicado", new[] { "IdCompaniaReporta" });
            DropTable("dbo.Roles");
            DropTable("dbo.Empleados");
            DropTable("dbo.Radicado");
            DropTable("dbo.Companias");
        }
    }
}
